# Generated by Django 6.0.4 on 2026-04-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('introduction', 'Introduction'), ('detailed_explanation', 'Detailed Explanation'), ('additional_resources', 'Additional Resources')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='topics.topic')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
