# Generated by Django 6.0.4 on 2026-04-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_sections', '0001_initial'),
        ('topics', '0002_alter_topic_is_published_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='topicsection',
            index=models.Index(fields=['topic', 'section_type', 'sort_order'], name='topic_secti_topic_i_e573d0_idx'),
        ),
        migrations.AddIndex(
            model_name='topicsection',
            index=models.Index(fields=['topic', 'sort_order'], name='topic_secti_topic_i_fe3992_idx'),
        ),
    ]
