# Generated by Django 6.0.4 on 2026-04-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_published', 'title'], name='topics_topi_is_publ_970a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['created_at'], name='topics_topi_created_f136b9_idx'),
        ),
    ]
