# Generated by Django 6.0.4 on 2026-04-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('video', 'Video'), ('youtube', 'YouTube')], max_length=20)),
                ('text_content', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='topics.topic')),
            ],
            options={
                'ordering': ['resource_type', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConceptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('popup_title', models.CharField(blank=True, max_length=255)),
                ('popup_text', models.TextField(blank=True)),
                ('popup_audio_url', models.URLField(blank=True)),
                ('popup_video_url', models.URLField(blank=True)),
                ('popup_youtube_url', models.URLField(blank=True)),
                ('popup_image_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_links', to='resources.topicresource')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
