# Generated by Django 6.0.4 on 2026-04-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('topics', '0002_alter_topic_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicresource',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='conceptlink',
            index=models.Index(fields=['topic_resource', 'sort_order'], name='resources_c_topic_r_7f050a_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptlink',
            index=models.Index(fields=['topic_resource', 'start_offset'], name='resources_c_topic_r_374fac_idx'),
        ),
        migrations.AddIndex(
            model_name='topicresource',
            index=models.Index(fields=['topic', 'resource_type', 'sort_order'], name='resources_t_topic_i_857118_idx'),
        ),
        migrations.AddIndex(
            model_name='topicresource',
            index=models.Index(fields=['topic', 'is_featured'], name='resources_t_topic_i_e384fc_idx'),
        ),
        migrations.AddIndex(
            model_name='topicresource',
            index=models.Index(fields=['created_at'], name='resources_t_created_2d36f9_idx'),
        ),
    ]
